# Generated by Django 5.2.7 on 2025-11-06 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adoption", "0002_rename_posted_at_adoptionpost_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "housing_type",
                    models.CharField(
                        help_text="e.g., House, Apartment, Condo", max_length=100
                    ),
                ),
                (
                    "owns_or_rents",
                    models.CharField(
                        choices=[("own", "Own"), ("rent", "Rent")], max_length=20
                    ),
                ),
                ("has_yard", models.BooleanField(default=False)),
                (
                    "landlord_approval",
                    models.BooleanField(
                        default=False,
                        help_text="If renting, do you have landlord approval?",
                    ),
                ),
                ("has_pets_currently", models.BooleanField(default=False)),
                (
                    "current_pets_description",
                    models.TextField(
                        blank=True, help_text="Describe your current pets"
                    ),
                ),
                (
                    "previous_pet_experience",
                    models.TextField(
                        help_text="Describe your previous experience with pets"
                    ),
                ),
                (
                    "why_adopt",
                    models.TextField(help_text="Why do you want to adopt this pet?"),
                ),
                (
                    "daily_care_plan",
                    models.TextField(help_text="How will you care for this pet daily?"),
                ),
                (
                    "veterinarian_info",
                    models.TextField(
                        blank=True,
                        help_text="Your veterinarian's contact information (optional)",
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True, help_text="Personal references (optional)"
                    ),
                ),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adoption_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="adoption.adoptionpost",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("adoption_post", "requester")},
            },
        ),
    ]
