# Generated by Django 5.2.7 on 2025-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_remove_petprofile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="petprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="petprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="pet_profiles/"),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="privacy_settings",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("FRIENDS", "Friends Only"),
                    ("PRIVATE", "Private"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="petprofile",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in lbs",
                max_digits=6,
                null=True,
            ),
        ),
    ]
