# Generated by Django 5.2.7 on 2025-11-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_petprofile_bio_petprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="petprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
