name: Django Tests

on:
  push:
    branches: [ main, adoption_and_community_tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        cd project
        python manage.py migrate --noinput

    - name: Run community and messaging tests
      run: |
        cd project
        python manage.py test community messaging -v 2
